name: Build & Deploy Game

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'
      - '.gitignore'
      - '**.md'

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GODOT_VERSION: "4.2.2"
  ITCH_PROJECT_NAME: "gametemplate"
  ITCH_USERNAME: "comigor"

jobs:
  export_game:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.game_version.outputs.version }}
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get game version
        id: game_version
        run: |
          cat ./project.godot | grep 'config/version' | sed -E 's/.*config.version="([^"]+)".*/\1/g' > version.txt
          echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"

      - name: export game
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/${{ env.GODOT_VERSION }}/Godot_v${{ env.GODOT_VERSION }}-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true
          cache: true

      - name: create release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ steps.game_version.outputs.version }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
          allowUpdates: true

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.export.outputs.archive_directory }}/*
          overwrite: true

  publish_itch:
    needs: export_game
    if: ${{ contains(github.ref, 'master') }}
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
      - name: setup butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: publish to itch
        run: |
          ./butler push artifact/Windows.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:win --assume-yes --userversion=${{ needs.export_game.outputs.version }}
          ./butler push artifact/LinuxX11.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:amd64 --assume-yes --userversion=${{ needs.export_game.outputs.version }}
          ./butler push artifact/Web.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:web --assume-yes --userversion=${{ needs.export_game.outputs.version }}
